---
title: "data_filtering_exp1"
author: "Nikolas McNeal"
date: "5/16/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#setwd("/users/PAS1962/nikolasmcneal/R/")
#df1 <- rbind(acc_data, val_data) %>% select(c(skew, subject)) %>% distinct()
df1 <- rbind(acc_data, val_data) %>% distinct() 
#%>% filter(trial_type=="blocks-exp")
# filter data so that it only includes participants in the first block



# filtering out - we check if participants are above chance, check outliers
# Blair will send code, check accuracy at usbject-level, if not above chance, remove
# then past that, filter out RTs too fast too slow.



#acc2 = read.csv("/Users/nikolasmcneal/Downloads/Accuracy-Condition-Data_Filtered_3.3.2023.csv")
#acc2$cond = "acc"
#val2 = read.csv("/Users/nikolasmcneal/Downloads/Value-Condition-Data_Filtered_3.3.2023.csv")
#val2$cond = "val"
#df2 = rbind(acc2, val2)





# we add the skew from my df to the cleaned data
#new.df = merge(df1, df2, by = 'subject')



new.df <- df1
```

```{r}
#write.csv(new.df, "/Users/nikolasmcneal/RStudio Workspace/Color_Discrimination/Exp1/exp1skew.csv", row.names=FALSE)
```



```{r}
new.df = read.csv("/Users/nikolasmcneal/RStudio Workspace/Color_Discrimination/Exp1/exp1skew.csv")

df <- new.df

df = df %>%
  group_by(subject) %>%
  mutate(trial_total = 1:n(),
         order = ifelse(min(trial_total[task=="experiment_FR"]) < min(trial_total[task=="experiment_VB"]), "FR_VB", "VB_FR"
  
                        )
         )

df
write.csv(df, "/Users/nikolasmcneal/RStudio Workspace/Color_Discrimination/Exp1/exp1skew.csv", row.names=FALSE)
```




```{r}

new.df = read.csv("/Users/nikolasmcneal/RStudio Workspace/Color_Discrimination/Exp1/exp1skew.csv")
new.df <- new.df %>% distinct() %>% filter(trial_type=="blocks-exp")

tempElimFC<-lapply(unique(new.df$subject),function(x){
  Elim<-matrix(0,ncol=4,nrow=1)
  temp<-new.df[new.df$subject==x,]
  Elim[1,1]<-x
  choiceLogit<-glm(accuracy~absVD*OV+I(OV^2), 
                   family = binomial(link=logit),
                   data = temp)
  c<-coef(choiceLogit)
  Elim[1,2]<-round(c[2],3) #slope coefficient (absVD)
  Elim[1,3]<-round(coef(summary(choiceLogit))[2,4],3) #pvalue
  Elim[1,4]<-ifelse(Elim[1,3]<.05 & Elim[1,2]>0,"keep","elim")
  ae<-as.data.frame(Elim)
  colnames(ae)<-c("SubjID",
                  "absVD_logitSlope","absVD_p","absVD_action")
  return(ae)
})

elimFC<-rbind.fill(tempElimFC)

good_ids = elimFC[elimFC[,4]=="keep",1,]


choiceDat_filtered <- new.df[new.df$subject %in% good_ids,]


choiceDat_filtered


#Here's code snippet for eliminating RT outliers

allDat4_filtered <- 
  choiceDat_filtered%>%
  group_by(subject, Phase) %>%
  filter(between(Timestamp,max(.250,quantile(Timestamp, .25)-(1.5*IQR(Timestamp))),
                 quantile(Timestamp, .75)+(1.5*IQR(Timestamp))))


new.df <- choiceDat_filtered
```


